/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.restaurante;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;


/**
 *
 * @author Raquel
 */
public class Menu1 extends javax.swing.JFrame {
    int contador =0;
    /**
     * Creates new form Menu1
     */
    private int rows;
    DefaultListModel model;
    
    //public String dato1 = "";
    
    double contotal=0;
    
    DefaultTableModel tablam = new DefaultTableModel();
    
    DefaultListModel dm = new DefaultListModel();
    DefaultListModel dm2 = new DefaultListModel();
    DefaultListModel dm3 = new DefaultListModel();
    DefaultListModel dm4 = new DefaultListModel();
    
    public Menu1() {
        initComponents();
        
        jTextField3.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        
        //Agregar la columna a la tabla
        tablam.addColumn("Producto");
        tablam.addColumn("Precio");
        tablam.addColumn("Cantidad");
        tablam.addColumn("Total");
        jTable1.setModel(tablam);
        
        //Agregar elementos a la lista
        
        jList1.setModel(dm);
        dm.addElement("Formagio");
        dm.addElement("Mortadela");
        dm.addElement("Nutella");
        
        jList2.setModel(dm2);
        dm2.addElement("Del Bosco");
        dm2.addElement("Caesar");
        dm2.addElement("Mista");
        
        jList3.setModel(dm3);
        dm3.addElement("Gelato");
        dm3.addElement("Tiramisu");
        dm3.addElement("Cheesecake");
        
        jList4.setModel(dm4);
        dm4.addElement("Birra");
        dm4.addElement("Aranciata");
        dm4.addElement("Shakerato");
        
        
    }
    
    private void add(String name){
        
        if(jCheckBox1.isSelected()){
            jList1.setModel(dm);
            dm.addElement(name);
        }
        
        else if (jCheckBox2.isSelected()){
            
            jList2.setModel(dm2);
            dm2.addElement(name);
        
        }
        else if (jCheckBox3.isSelected()){
            
            jList3.setModel(dm3);
            dm3.addElement(name);
        
        }
        else if (jCheckBox4.isSelected()){
            
            jList4.setModel(dm4);
            dm4.addElement(name);
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel15.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
        jLabel15.setText("Casina del bosco");

        jTextField3.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jTextField3.setText("50");
        jTextField3.setBorder(null);
        jTextField3.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel10.setText("$");

        jCheckBox1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jCheckBox1.setText("Piadina");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jList1.setEnabled(false);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Cantidad:");

        jTextField2.setText("1");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jTextField1.setText("0");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1.setText("Total : $");

        jCheckBox2.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jCheckBox2.setText("Insalate");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jList2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jList2.setEnabled(false);
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        jTextField5.setText("1");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Cantidad:");

        jTextField6.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jTextField6.setText("25");
        jTextField6.setBorder(null);
        jTextField6.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel12.setText("$");

        jCheckBox3.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jCheckBox3.setText("Dolci");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jTextField7.setText("30");
        jTextField7.setBorder(null);
        jTextField7.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel13.setText("$");

        jList3.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jList3.setEnabled(false);
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList3);

        jTextField8.setText("1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Cantidad:");

        jCheckBox4.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jCheckBox4.setText("Bevande");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jList4.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jList4.setEnabled(false);
        jList4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jList4);

        jTextField9.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jTextField9.setText("20");
        jTextField9.setBorder(null);
        jTextField9.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel16.setText("$");

        jTextField10.setText("1");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Cantidad:");

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel2.setText("Contador:");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField11.setEnabled(false);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Agregar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Borrar");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Modificar");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jCheckBox5.setText("Administrador");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raquel\\Desktop\\CdB-sito-2015-logo-p01-01.png")); // NOI18N

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Pagar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Enviar ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextField12.setEnabled(false);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField13.setEnabled(false);

        jTextField14.setEnabled(false);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("Modificar");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Regresar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Borrar Linea");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel4.setText("Fila");

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel5.setText("Texto");

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel6.setText("Columna");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(81, 81, 81)
                                                .addComponent(jTextField12))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5))
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField13)
                                                    .addComponent(jTextField14))))
                                        .addGap(42, 42, 42)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(39, 39, 39)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(37, 37, 37)
                                .addComponent(jButton2)
                                .addGap(65, 65, 65)
                                .addComponent(jButton1)))
                        .addGap(59, 59, 59)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10)
                        .addGap(31, 31, 31)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jCheckBox5)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(31, 31, 31)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(69, 69, 69))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(69, 69, 69))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(31, 31, 31)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(69, 69, 69))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(31, 31, 31)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(69, 69, 69))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(64, 64, 64))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton4)
                                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton6)
                                            .addComponent(jButton5))
                                        .addGap(1, 90, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox2)
                                .addComponent(jCheckBox3)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jButton11))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton9)
                                            .addComponent(jLabel5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel16))
                                            .addGap(63, 63, 63)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel17)
                                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jButton6))
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        boolean selectedP = jCheckBox1.isSelected();

        if(selectedP){
            jCheckBox1.isSelected();
            jTextField3.setEnabled(true);
            jList1.setEnabled(true);

           jCheckBox2.setEnabled(false);
           jCheckBox3.setEnabled(false);
          jCheckBox4.setEnabled(false);

        }
        else{
            jCheckBox1.isSelected();
            //jTextField3.setEnabled(false);
            jList1.setEnabled(false);

           jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(jCheckBox1.isSelected()){
            
            if(jList1.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Selecciona un platillo");
            }

            else{
                double precio = Integer.parseInt(jTextField3.getText());
                int cantidad = Integer.parseInt(jTextField2.getText());
                double total;
                total = precio * cantidad;
                contotal = contotal + total;
                this.jTextField1.setText(contotal +"");
                Vector datos = new Vector();
                datos.addElement(this.jList1.getSelectedValue());
                datos.addElement(jTextField3.getText());
                datos.addElement(jTextField2.getText());
                datos.addElement(total +"");
                tablam.addRow(datos);
                jTable1.setModel(tablam);
                jTextField4.setText(tablam.getRowCount()+"");
                
                }

         }
        else if(jCheckBox2.isSelected()){
            
            if(jList2.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Selecciona un platillo");
            }
            else{
                double precio = Integer.parseInt(jTextField6.getText());
                int cantidad = Integer.parseInt(jTextField5.getText());
                double total;
                total = precio * cantidad;
                contotal = contotal + total;
                this.jTextField1.setText(contotal +"");
                Vector datos = new Vector();
                datos.addElement(this.jList2.getSelectedValue());
                datos.addElement(jTextField6.getText());
                datos.addElement(jTextField5.getText());
                datos.addElement(total +"");
                tablam.addRow(datos);
                jTable1.setModel(tablam);
                jTextField4.setText(tablam.getRowCount()+"");
            }
        }
        else if(jCheckBox3.isSelected()){
            
            if(jList3.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Selecciona un platillo");
            }
            else{
                double precio = Integer.parseInt(jTextField7.getText());
                int cantidad = Integer.parseInt(jTextField8.getText());
                double total;
                total = precio * cantidad;
                contotal = contotal + total;
                this.jTextField1.setText(contotal +"");
                Vector datos = new Vector();
                datos.addElement(this.jList3.getSelectedValue());
                datos.addElement(jTextField7.getText());
                datos.addElement(jTextField8.getText());
                datos.addElement(total +"");
                tablam.addRow(datos);
                jTable1.setModel(tablam);
                jTextField4.setText(tablam.getRowCount()+"");
            }
        }
        else if(jCheckBox4.isSelected()){
            
            if(jList4.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Selecciona un platillo");
            }
            else{
                double precio = Integer.parseInt(jTextField9.getText());
                int cantidad = Integer.parseInt(jTextField10.getText());
                double total;
                total = precio * cantidad;
                contotal = contotal + total;
                this.jTextField1.setText(contotal +"");
                Vector datos = new Vector();
                datos.addElement(this.jList4.getSelectedValue());
                datos.addElement(jTextField9.getText());
                datos.addElement(jTextField10.getText());
                datos.addElement(total +"");
                tablam.addRow(datos);
                jTable1.setModel(tablam);
                jTextField4.setText(tablam.getRowCount()+"");
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        
        boolean selectedI = jCheckBox2.isSelected();
        if(selectedI){
            if(jCheckBox2.isSelected()){
               jTextField6.setEnabled(true);
               jList2.setEnabled(true); 
               
               jCheckBox1.setEnabled(false);
               jCheckBox3.setEnabled(false);
               jCheckBox4.setEnabled(false);
            }
            else{
                //Agregar mensaje por si no se selecciono alimento                
            }
            
        }
        else{
            jCheckBox2.isSelected();
            //jTextField6.setEnabled(false);
            jList2.setEnabled(false);
            
            jCheckBox1.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
        }
        
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        
        boolean selectedD = jCheckBox3.isSelected();
        if(selectedD){
            jCheckBox3.isSelected();
            jTextField7.setEnabled(true);
            jList3.setEnabled(true);
            
            jCheckBox1.setEnabled(false);
            jCheckBox2.setEnabled(false);
            jCheckBox4.setEnabled(false);

        }
        else{
            jCheckBox3.isSelected();
            //jTextField8.setEnabled(false);
            jList3.setEnabled(false);
            
            jCheckBox1.setEnabled(true);
            jCheckBox2.setEnabled(true);
            jCheckBox4.setEnabled(true);
        }
        
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        
        boolean selectedB = jCheckBox4.isSelected();
        if(selectedB){
            jCheckBox4.isSelected();
            jTextField9.setEnabled(true);
            jList4.setEnabled(true);
            
            jCheckBox1.setEnabled(false);
            jCheckBox2.setEnabled(false);
            jCheckBox3.setEnabled(false);

        }
        else{
            jCheckBox4.isSelected();
            //jTextField10.setEnabled(false);
            jList4.setEnabled(false);
            
            jCheckBox1.setEnabled(true);
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
        }
        
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
                {
                    String nombre = "";
                    JFileChooser MI_ARCHIVO=new JFileChooser(System.getProperty("user.dir"));
                    MI_ARCHIVO.showSaveDialog(this);
                    
                    File GUARDAR =MI_ARCHIVO.getSelectedFile();
                if(GUARDAR != null)
                {
                    
                    nombre=MI_ARCHIVO.getSelectedFile().getName();
                    FileWriter GUARDADO=new FileWriter(GUARDAR);
                    
                   for(int i = 0 ; i < jTable1.getColumnCount() ; i++){
                       GUARDADO.write(jTable1.getColumnName(i));
                       GUARDADO.write("\t");
                       
                   }
                   for(int i=0; i< jTable1.getRowCount(); i++){
                       GUARDADO.write("\r\n");
                       for(int j=0; j< jTable1.getColumnCount(); j++){
                           
                           GUARDADO.write((String)(jTable1.getValueAt(i, j)));
                           GUARDADO.write("\t");
                           
                           
                       }
                   }
                    
                    GUARDADO.close();
                }
                }
                catch(IOException exp)
                {
                    System.out.println(exp);
                    
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
//        if(jTable1.getSelectedRow()==-1){
//            if(jTable1.getRowCount()==0){
//                JOptionPane.showMessageDialog(this, "La tabla esta vacia. Ingresa producto");
//            }
//            else{
//                JOptionPane.showMessageDialog(this, "Selecciona un producto");
//            }
//            
//        }else{
//            model.removeRow(jTable1.getSelectedRow());
//            rows--;
//            jTextField1.setText("");
//            jTextField4.setText("");
//        }

          int cantidadfilas = jTable1.getRowCount();
          for( int i= cantidadfilas-1; i>=0; i--){
              tablam.removeRow(i);
              //jTextField1.setText("");
              jTextField11.setText("");
              
              
              int valor =0;
               jTextField1.setText(Integer.toString(valor)); 
              contotal =0;
              
          }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        if(jCheckBox1.isSelected()){
            
            add(jTextField11.getText());
            jTextField11.setText("");
        }
        else if(jCheckBox2.isSelected()){
            
            add(jTextField11.getText());
            jTextField11.setText("");
        }
        else if(jCheckBox3.isSelected()){
            
            add(jTextField11.getText());
            jTextField11.setText("");
        }
        else if(jCheckBox4.isSelected()){
            
            add(jTextField11.getText());
            jTextField11.setText("");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        if(jCheckBox1.isSelected()){
         
            int index = jList1.getSelectedIndex();
            dm.removeElementAt(index);
            jTextField11.setText("");
        }
        else if(jCheckBox2.isSelected()){
            int index = jList2.getSelectedIndex();
            dm2.removeElementAt(index);
            jTextField11.setText("");
        }
        else if(jCheckBox3.isSelected()){
            int index = jList3.getSelectedIndex();
            dm3.removeElementAt(index);
            jTextField11.setText("");
        }
        else if(jCheckBox4.isSelected()){
            int index = jList4.getSelectedIndex();
            dm4.removeElementAt(index);
            jTextField11.setText("");
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        if(jCheckBox1.isSelected()){
            int index = jList1.getSelectedIndex();
            dm.setElementAt(jTextField11.getText(), index);
            jTextField11.setText("");
        }
        else if (jCheckBox2.isSelected()){
            int index = jList2.getSelectedIndex();
            dm2.setElementAt(jTextField11.getText(), index);
            jTextField11.setText("");
        }
        else if (jCheckBox3.isSelected()){
            int index = jList3.getSelectedIndex();
            dm3.setElementAt(jTextField11.getText(), index);
            jTextField11.setText("");
        }
        else if (jCheckBox4.isSelected()){
            int index = jList4.getSelectedIndex();
            dm4.setElementAt(jTextField11.getText(), index);
            jTextField11.setText("");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String selected = jList1.getSelectedValue().toString();
        jTextField11.setText(selected);
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        String selected = jList2.getSelectedValue().toString();
        jTextField11.setText(selected);
    }//GEN-LAST:event_jList2MouseClicked

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        String selected = jList3.getSelectedValue().toString();
        jTextField11.setText(selected);
    }//GEN-LAST:event_jList3MouseClicked

    private void jList4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList4MouseClicked
        String selected = jList4.getSelectedValue().toString();
        jTextField11.setText(selected);
    }//GEN-LAST:event_jList4MouseClicked

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        
        if(jCheckBox5.isSelected()){
        String user = JOptionPane.showInputDialog(null, "Usuario");
		String password = JOptionPane.showInputDialog(null, "Contraseña");

		if ("Administrador".equals(user) && "Contraseña".equals(password)) {
			JOptionPane.showMessageDialog(null, "login ok");
                        jTextField11.setEnabled(true);
                        jButton4.setEnabled(true);
                        jButton5.setEnabled(true);
                        jButton6.setEnabled(true);
                        jButton9.setEnabled(true);
                        jTextField12.setEnabled(true);
                        jTextField13.setEnabled(true);
                        jTextField14.setEnabled(true);
                        jTextField3.setEditable(true);
                        jTextField6.setEditable(true);
                        jTextField7.setEditable(true);
                        jTextField9.setEditable(true);
                        jTextField12.setEditable(true);
                        jTextField13.setEditable(true);
                        jTextField14.setEditable(true);
		}else {
			JOptionPane.showMessageDialog(null, "login failed");
                        jTextField11.setEnabled(false);
                        jButton4.setEnabled(false);
                        jButton5.setEnabled(false);
                        jButton6.setEnabled(false);
                        jButton9.setEnabled(false);
                        jTextField12.setEnabled(false);
                        jTextField13.setEnabled(false);
                        jTextField14.setEnabled(false);
                        jTextField3.setEditable(false);
                        jTextField6.setEditable(false);
                        jTextField7.setEditable(false);
                        jTextField9.setEditable(false);
                        jTextField12.setEditable(false);
                        jTextField13.setEditable(false);
                        jTextField14.setEditable(false);
		}
        }
        else 
        {
            jTextField11.setEnabled(false);
                        jButton4.setEnabled(false);
                        jButton5.setEnabled(false);
                        jButton6.setEnabled(false);
                        jButton9.setEnabled(false);
                        jTextField3.setEditable(false);
                        jTextField6.setEditable(false);
                        jTextField7.setEditable(false);
                        jTextField9.setEditable(false);
                        jTextField12.setEditable(false);
                        jTextField13.setEditable(false);
                        jTextField14.setEditable(false);
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //                    Object[] options = { "Efectivo", "Tarjeta" };
        //                    JOptionPane.showOptionDialog(null, "Selecciona la forma de pago", "Warning",
            //                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
            //                    null, options, options[0]);
        int n1, n2;
        Object pago = JOptionPane.showInputDialog(null,"Seleccione una forma de pago",
            "Pago", JOptionPane.QUESTION_MESSAGE, null,
            new Object[] { "Seleccione","Efectivo", "Tarjeta de credito", "Tarjeta de debito" },"Seleccione");
        if(pago.equals("Efectivo")){
            n1 = Integer.parseInt(JOptionPane.showInputDialog("ingresa el billete dado"));
            n2 = Integer.parseInt(JOptionPane.showInputDialog("ingresa el total de la cuenta"));
            JOptionPane.showMessageDialog(this, "Cambio: " + (n1-n2));
        }
        else if (pago.equals("Tarjeta de credito")){
            JOptionPane.showInputDialog("Ingresa el numero de tarjeta");
            JOptionPane.showMessageDialog(this, "Tarjeta aceptada");
        }
        else if (pago.equals("Tarjeta de debito")){
            JOptionPane.showInputDialog("Ingresa el numero de tarjeta");
            JOptionPane.showMessageDialog(this, "Tarjeta aceptada");
        }
        JOptionPane.showMessageDialog(null, "Pago realizado");

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JOptionPane.showMessageDialog(null, "Pedido enviado a la cocina");
       
        FileWriter fichero = null;
        try {
            contador = contador + 1;
            fichero = new FileWriter("C:\\Users\\Raquel\\Desktop\\cont.txt",true);
            //guardar en el fichero
            fichero.write("\r\n");
            fichero.write(contador + " ");
            fichero.write("\r\n");
            
            for(int i = 0 ; i < jTable1.getColumnCount() ; i++){
                       fichero.write(jTable1.getColumnName(i));
                       fichero.write("\t");
                       
                   }
                   for(int i=0; i< jTable1.getRowCount(); i++){
                       fichero.write("\r\n");
                       for(int j=0; j< jTable1.getColumnCount(); j++){
                           
                           fichero.write((String)(jTable1.getValueAt(i, j)));
                           fichero.write("\t");
                           
                           
                       }
                   }
            fichero.close(); 
        }
        catch(Exception ex){
            System.out.println("Mensaje de la excepción: " + ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int fila = Integer.parseInt(jTextField12.getText());
        int col = Integer.parseInt(jTextField13.getText());
        tablam.setValueAt(jTextField14.getText(), fila, col);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         //Abir
         Usuarios jFrame = new Usuarios();
                        jFrame.setVisible(true);
                        hide();
         
         
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "La tabla esta vacia. Ingresa producto");
            }
            else{
                JOptionPane.showMessageDialog(this, "Selecciona un producto");
            }
            
        }else{
            model.removeRow(jTable1.getSelectedRow());
            rows--;
            jTextField1.setText("");
            
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
